#include "config.h"

#include "common.h"

/* favicon to use */
const char* favicon     = "favicon.svg";
const char* favicontype = "image/svg+xml";

/* logo to use in header*/
const char* logoicon = "logo.svg";

/* stylesheet to use */
const char* stylesheet = "style.css";

/* where to put the html files relative to repodir */
const char* destination = "";

/* command to execute to highlight a file, use `cat` to disable */
const char* highlightcmd = "chroma --html --html-only --html-inline-styles --style=xcode --lexer=$type";

/* name of cache directory for highlighting */
const char* highlightcache = ".gitin/files";

long long maxfilesize = 1e+6;    // 1MB

/* name of cache directory for commit */
const char* commitcache = NULL;    //".gitincommits";

const char* sitename = "My Repositories";

const char* footertext = "Generated by <i><code>gitin</code></i>!";

/* maximum of commits to log, -1 indicates not used */
long long nlogcommits = -1;

/* files to use as lisense or readme, these will be pinned in the header */
const char* pinfiles[] = {
	"LICENSE", "LICENSE.md", "COPYING", "README", "README.md",
};
int npinfiles = LEN(pinfiles);

const char* configfile = "gitin.conf";
