extern const char* highlightcmd;
extern const char* logoicon;
extern const char* favicon;
extern const char* favicontype;
extern const char* highlightcache;
extern const char* commitcache;
extern const char* destination;
extern const char* pinfiles[];
extern int         pinfileslen;
extern const char* indexfile;
extern const char* stylesheet;
extern long long   nlogcommits;
extern const char* sitename;
extern const char* footertext;
